

import os
from groq import Groq
from dotenv import load_dotenv
from obfuscation import get_fake_schema_description

load_dotenv()


client = Groq(api_key=os.getenv("GROQ_API_KEY"))


MODEL_NAME = "llama-3.3-70b-versatile"

TEST_MODE = os.getenv("TEST_MODE", "false").lower() == "true"


def generate_sql_from_question(user_question):
    """
    Takes a plain English question like "How many orders were placed in March?"
    and returns a SQL query string using FAKE table/column names
    (e.g. SELECT COUNT(*) FROM table_C WHERE ...).

    This fake SQL is NOT run yet -- validator.py and obfuscation.py
    will process it further before it touches the real database.
    """

    if TEST_MODE:
        return "SELECT col_A2 FROM table_A WHERE col_A3 = 'Lucknow'"

    
    fake_schema = get_fake_schema_description()

  
    prompt = f"""You are a SQL generator. You will be given a database schema using
generic table and column names, and a question in plain English.

Your job: write ONE single MySQL SELECT query that answers the question,
using ONLY the table and column names provided in the schema below.

Rules:
- Only generate SELECT statements. Never write INSERT, UPDATE, DELETE, or DROP.
- Use only the exact table/column names given below -- do not invent new ones.
- Return ONLY the raw SQL query as plain text. No explanations, no markdown
  formatting, no ```sql code blocks -- just the query itself.

Schema:
{fake_schema}

Question: {user_question}

SQL query:"""

    
    response = client.chat.completions.create(
        model=MODEL_NAME,
        messages=[
            {"role": "user", "content": prompt}
        ],
        temperature=0.2
    )

    raw_sql = response.choices[0].message.content.strip()
    raw_sql = raw_sql.replace("```sql", "").replace("```", "").strip()

    return raw_sql


if __name__ == "__main__":
    test_question = "Show me the names of all customers from Lucknow"
    print("Question:", test_question)

    fake_sql = generate_sql_from_question(test_question)
    print("\nFake SQL generated by AI:")
    print(fake_sql)