# ============================================
# nl_to_sql.py
#
# This is the heart of the project: it takes the user's plain English
# question, combines it with our FAKE schema (from obfuscation.py),
# sends both to an AI model via Groq, and gets back a SQL query --
# still using FAKE table/column names at this point.
#
# We switched from Gemini to Groq because Gemini's free tier
# currently allows only ~20 requests/day, while Groq's free tier
# allows around 1,000 requests/day -- much safer for live demos.
# ============================================

import os
from groq import Groq
from dotenv import load_dotenv
from obfuscation import get_fake_schema_description

load_dotenv()

# ----------------------------------------------
# Create ONE client object that talks to Groq.
# It reads GROQ_API_KEY from the environment automatically.
# ----------------------------------------------
client = Groq(api_key=os.getenv("GROQ_API_KEY"))

# Llama 3.3 70B is fast, free-tier friendly, and good at structured
# tasks like SQL generation.
MODEL_NAME = "llama-3.3-70b-versatile"

# ----------------------------------------------
# TEST MODE: when TEST_MODE=true is set in .env, this file skips
# calling the real AI entirely and returns a hardcoded fake response
# instead. Lets you test Flask, frontend, database, etc. without
# using up API quota. Set TEST_MODE=false when you want real answers.
# ----------------------------------------------
TEST_MODE = os.getenv("TEST_MODE", "false").lower() == "true"


def generate_sql_from_question(user_question):
    """
    Takes a plain English question like "How many orders were placed in March?"
    and returns a SQL query string using FAKE table/column names
    (e.g. SELECT COUNT(*) FROM table_C WHERE ...).

    This fake SQL is NOT run yet -- validator.py and obfuscation.py
    will process it further before it touches the real database.
    """

    if TEST_MODE:
        return "SELECT col_A2 FROM table_A WHERE col_A3 = 'Lucknow'"

    # Get our fake schema description (table_A, col_A1, etc.)
    # This is the ONLY information about our database structure
    # that the AI ever sees.
    fake_schema = get_fake_schema_description()

    # Being very explicit here matters a lot -- vague prompts
    # produce unreliable SQL.
    prompt = f"""You are a SQL generator. You will be given a database schema using
generic table and column names, and a question in plain English.

Your job: write ONE single MySQL SELECT query that answers the question,
using ONLY the table and column names provided in the schema below.

Rules:
- Only generate SELECT statements. Never write INSERT, UPDATE, DELETE, or DROP.
- Use only the exact table/column names given below -- do not invent new ones.
- Return ONLY the raw SQL query as plain text. No explanations, no markdown
  formatting, no ```sql code blocks -- just the query itself.

Schema:
{fake_schema}

Question: {user_question}

SQL query:"""

    # Groq uses the same "chat messages" format as OpenAI's API.
    response = client.chat.completions.create(
        model=MODEL_NAME,
        messages=[
            {"role": "user", "content": prompt}
        ],
        temperature=0.2
    )

    raw_sql = response.choices[0].message.content.strip()
    raw_sql = raw_sql.replace("```sql", "").replace("```", "").strip()

    return raw_sql


if __name__ == "__main__":
    test_question = "Show me the names of all customers from Lucknow"
    print("Question:", test_question)

    fake_sql = generate_sql_from_question(test_question)
    print("\nFake SQL generated by AI:")
    print(fake_sql)